### ISSUE TITLE
Acrobat Reader : plus nécessaire

### ISSUE THREAD

**Issue by dbitouze** [jjfPCSI1/animations_latex#1]
Merci beaucoup pour ces très intéressantes animations !

Dans votre README, vous dites :

> ATTENTION: le package animate utilise certaines invocations de magie noire que seul Acrobat Reader est capable de correctement rendre à l'écran. Il faut donc forcément l'installer pour visualiser les animations correspondantes.

Ça n'est en fait plus le cas : l'afficheur PDF [`Okular`](https://okular.kde.org/fr/) sous GNU/Linux (et aussi Windows), qui est un logiciel libre, permet de visualiser ces animations.

**Comment by jjfPCSI1** [comment]
Merci @dbitouze pour la précision. Je l'ai rajoutée dans le README.
